# Generated by Django 4.2.7 on 2026-08-08 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_weight_kg', models.FloatField(verbose_name='Poids brut (kg)')),
                ('filtered_weight_kg', models.FloatField(verbose_name='Poids filtré (kg)')),
                ('calibrated_weight_kg', models.FloatField(verbose_name='Poids calibré (kg)')),
                ('is_overloaded', models.BooleanField(default=False, verbose_name='Surcharge')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_measurements', to='trips.trip', verbose_name='Trajet')),
            ],
            options={
                'verbose_name': 'Mesure de poids',
                'verbose_name_plural': 'Mesures de poids',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['trip', 'timestamp'], name='measurement_trip_id_ddd07e_idx')],
            },
        ),
        migrations.CreateModel(
            name='GPSPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Altitude (m)')),
                ('speed_kmh', models.FloatField(verbose_name='Vitesse (km/h)')),
                ('heading', models.IntegerField(blank=True, null=True, verbose_name='Cap (°)')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Précision (m)')),
                ('is_stationary', models.BooleanField(default=False, verbose_name="À l'arrêt")),
                ('is_abnormal_stop', models.BooleanField(default=False, verbose_name='Arrêt anormal')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_positions', to='trips.trip', verbose_name='Trajet')),
            ],
            options={
                'verbose_name': 'Position GPS',
                'verbose_name_plural': 'Positions GPS',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['trip', 'timestamp'], name='measurement_trip_id_2a943a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_level_percent', models.FloatField(verbose_name='Niveau carburant (%)')),
                ('fuel_level_liters', models.FloatField(verbose_name='Niveau carburant (L)')),
                ('speed_kmh', models.FloatField(blank=True, null=True, verbose_name='Vitesse (km/h)')),
                ('engine_rpm', models.IntegerField(blank=True, null=True, verbose_name='Régime moteur')),
                ('engine_load', models.FloatField(blank=True, null=True, verbose_name='Charge moteur (%)')),
                ('is_fuel_theft', models.BooleanField(default=False, verbose_name='Vol carburant détecté')),
                ('fuel_drop_amount', models.FloatField(default=0, verbose_name='Quantité volée (L)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_measurements', to='trips.trip', verbose_name='Trajet')),
            ],
            options={
                'verbose_name': 'Mesure carburant',
                'verbose_name_plural': 'Mesures carburant',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['trip', 'timestamp'], name='measurement_trip_id_6e8c66_idx')],
            },
        ),
    ]
