# Generated by Django 4.2.7 on 2026-08-08 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trucks', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('OVERLOAD', 'Surcharge'), ('FUEL_THEFT', 'Vol carburant'), ('ABNORMAL_STOP', 'Arrêt anormal'), ('LOW_FUEL', 'Niveau carburant bas'), ('SPEEDING', 'Excès de vitesse'), ('MAINTENANCE', 'Maintenance requise')], max_length=20, verbose_name="Type d'alerte")),
                ('message', models.TextField(verbose_name='Message')),
                ('threshold_value', models.FloatField(verbose_name='Valeur seuil')),
                ('actual_value', models.FloatField(verbose_name='Valeur réelle')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RESOLVED', 'Résolu'), ('IGNORED', 'Ignoré'), ('IN_PROGRESS', 'En cours')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu à')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notes de résolution')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Déclenchée à')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trips.trip', verbose_name='Trajet')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trucks.truck', verbose_name='Camion')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['truck', 'status', 'triggered_at'], name='alerts_aler_truck_i_c43e89_idx'), models.Index(fields=['alert_type'], name='alerts_aler_alert_t_e287ad_idx'), models.Index(fields=['status'], name='alerts_aler_status_2a92cb_idx')],
            },
        ),
    ]
