# Generated by Django 4.2.7 on 2026-08-08 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Date du rapport')),
                ('total_trips', models.IntegerField(default=0, verbose_name='Nombre de trajets')),
                ('total_distance_km', models.FloatField(default=0, verbose_name='Distance totale (km)')),
                ('total_duration_hours', models.FloatField(default=0, verbose_name='Durée totale (h)')),
                ('total_weight_kg', models.FloatField(default=0, verbose_name='Poids total transporté (kg)')),
                ('avg_weight_kg', models.FloatField(default=0, verbose_name='Poids moyen (kg)')),
                ('total_fuel_consumed_l', models.FloatField(default=0, verbose_name='Consommation totale (L)')),
                ('avg_fuel_consumption_l_100km', models.FloatField(default=0, verbose_name='Consommation moyenne (L/100km)')),
                ('avg_fuel_per_ton_km', models.FloatField(default=0, verbose_name='Consommation par tonne (L/tonne)')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Recette totale')),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coût carburant')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Marge (%)')),
                ('total_alerts', models.IntegerField(default=0, verbose_name="Nombre d'alertes")),
                ('resolved_alerts', models.IntegerField(default=0, verbose_name='Alertes résolues')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/', verbose_name='Fichier PDF')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='PDF généré à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='trucks.truck', verbose_name='Camion')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-report_date'],
                'unique_together': {('truck', 'report_date')},
            },
        ),
    ]
