# Generated by Django 4.2.7 on 2026-08-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('OWNER', 'Propriétaire')], default='OWNER', max_length=20),
        ),
    ]
