# Generated by Django 4.2.7 on 2026-08-08 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('product_type', models.CharField(blank=True, max_length=100, verbose_name='Type de produit')),
                ('weight_kg', models.FloatField(verbose_name='Poids (kg)')),
                ('weight_verified', models.BooleanField(default=False, verbose_name='Poids vérifié')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='loadings/%Y/%m/%d/', verbose_name='Photo')),
                ('photo_taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Photo prise à')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validation propriétaire')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadings', to='trips.trip', verbose_name='Trajet')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_loadings', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Chargement',
                'verbose_name_plural': 'Chargements',
                'ordering': ['-created_at'],
            },
        ),
    ]
