# Generated by Django 4.2.7 on 2026-08-08 20:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Début du trajet')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin du trajet')),
                ('start_location', models.CharField(max_length=255, verbose_name='Lieu de départ')),
                ('end_location', models.CharField(blank=True, max_length=255, null=True, verbose_name="Lieu d'arrivée")),
                ('total_distance_km', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distance totale (km)')),
                ('total_fuel_consumed_l', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Consommation totale (L)')),
                ('avg_fuel_consumption_l_100km', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Consommation moyenne (L/100km)')),
                ('avg_fuel_per_ton_km', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Consommation par tonne (L/tonne)')),
                ('max_weight_kg', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids max (kg)')),
                ('avg_weight_kg', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids moyen (kg)')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='IN_PROGRESS', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trucks.truck', verbose_name='Camion')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['truck', 'start_time'], name='trips_trip_truck_i_4764a0_idx'), models.Index(fields=['status'], name='trips_trip_status_259ca6_idx'), models.Index(fields=['truck', 'status'], name='trips_trip_truck_i_392795_idx')],
            },
        ),
    ]
