# Generated by Django 4.2.7 on 2026-08-08 20:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ID Camion')),
                ('license_plate', models.CharField(max_length=20, verbose_name="Plaque d'immatriculation")),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('max_capacity_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacité max (kg)')),
                ('fuel_tank_capacity_l', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacité réservoir (L)')),
                ('overload_threshold_kg', models.FloatField(default=3000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seuil surcharge (kg)')),
                ('fuel_theft_threshold_l', models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seuil vol carburant (L)')),
                ('abnormal_stop_minutes', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Arrêt anormal (min)')),
                ('cost_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coût au km')),
                ('cost_per_liter', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coût au litre')),
                ('revenue_per_ton', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Recette par tonne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Camion',
                'verbose_name_plural': 'Camions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['truck_id'], name='trucks_truc_truck_i_8cc56c_idx'), models.Index(fields=['owner', 'is_active'], name='trucks_truc_owner_i_42ce49_idx')],
            },
        ),
    ]
